"""empty message

Revision ID: 1a7c813a17c2
Revises: 7bb11a24276
Create Date: 2014-05-14 01:41:03.495320

"""

# revision identifiers, used by Alembic.
revision = '1a7c813a17c2'
down_revision = '7bb11a24276'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sort_asin', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_item_sort_asin'), 'item', ['sort_asin'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_sort_asin'), table_name='item')
    op.drop_column('item', 'sort_asin')
    ### end Alembic commands ###
