"""empty message

Revision ID: 1ead68a53597
Revises: 348720abe06e
Create Date: 2014-05-11 17:12:04.427336

"""

# revision identifiers, used by Alembic.
revision = '1ead68a53597'
down_revision = '348720abe06e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
