"""empty message

Revision ID: 1fe914156ac0
Revises: 4480ecc50e04
Create Date: 2014-05-20 18:29:36.352416

"""

# revision identifiers, used by Alembic.
revision = '1fe914156ac0'
down_revision = '4480ecc50e04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sort_isbn', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_item_sort_isbn'), 'item', ['sort_isbn'], unique=False)

    #op.drop_column('item', 'sort_isbn13')
    #op.drop_column('item', 'sort_isbn10')
    #op.drop_index('ix_item_sort_isbn10', table_name='item')
    #op.drop_index('ix_item_sort_isbn13', table_name='item')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_sort_isbn13', 'item', ['sort_isbn13'], unique=False)
    op.create_index('ix_item_sort_isbn10', 'item', ['sort_isbn10'], unique=False)
    op.drop_index(op.f('ix_item_sort_isbn'), table_name='item')
    op.add_column('item', sa.Column('sort_isbn10', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('item', sa.Column('sort_isbn13', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('item', 'sort_isbn')
    ### end Alembic commands ###
