"""empty message

Revision ID: 2350803a5a2d
Revises: 1ead68a53597
Create Date: 2014-05-13 15:43:51.840049

"""

# revision identifiers, used by Alembic.
revision = '2350803a5a2d'
down_revision = '1ead68a53597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
