"""empty message

Revision ID: 7bb11a24276
Revises: 21589282102d
Create Date: 2014-05-13 18:28:46.214059

"""

# revision identifiers, used by Alembic.
revision = '7bb11a24276'
down_revision = '21589282102d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter')
    op.add_column('find', sa.Column('findvalue', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('find', 'findvalue')
    op.create_table('filter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('key', sa.VARCHAR(length=200), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('findvalue', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], [u'item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
